### PR TITLE
added comments to ada-matrix.py

### PR DESCRIPTION
**Pull request by adammhaile**

### CODE REVIEW

**Comment by PaintYourDragon** [comment]
Kickass. Thank you!

**Comment by adammhaile** [comment]
Welcome! Thanks for your library!

**Comment by adammhaile** [comment]
BTW... Am I missing something about brightness levels on these displays? BiblioPixel will scale the values internally... So, for example, white (255,255,255) scaled by 50% will be (128,128,128), but when I do this I see absolutely no change in brightness. I saw the SetPWMBits function (which I need to add support for in my driver... might help speed) but I don't guess that's for brightness specifically... I even scaled all my colors down to as far as 2% full brightness and the display was still just as bright.

**Comment by adammhaile** [comment]
Nevermind... I just realized I was running an animation that ignored brightness (at the benefit of better speed)... D'oh!

**Pull request merged**
